const USER_TYPE = {
  SYSTEM_ADMIN: 'SYSTEM_ADMIN',
  ORG_ADMIN: 'ORG_ADMIN',
  PROJECT_MANAGER: 'PROJECT_MANAGER',
  PERMANENT_WORKER: 'PERMANENT_WORKER',
  TEMPORARY_WORKER: 'TEMPORARY_WORKER',
};

const TASK_STATUS = {
  PENDING: 'PENDING',
  ASSIGNED: 'ASSIGNED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
};

const AVAILABILITY_STATUS = {
  AVAILABLE: 'AVAILABLE',
  UNAVAILABLE: 'UNAVAILABLE',
  ON_LEAVE: 'ON_LEAVE',
};

const SUBSCRIPTION_STATUS = {
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  CANCELLED: 'CANCELLED',
  EXPIRED: 'EXPIRED',
};

const ASSIGNMENT_TYPE = {
  MANUAL: 'MANUAL',
  AUTO: 'AUTO',
};

const LEAVE_TYPE = {
  ANNUAL: 'ANNUAL',
  MEDICAL: 'MEDICAL',
  UNPAID: 'UNPAID',
  OTHER: 'OTHER',
};

const LEAVE_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
};

const BILLING_STATUS = {
  PAID: 'PAID',
  UNPAID: 'UNPAID',
  REFUNDED: 'REFUNDED',
};

const FEEDBACK_STATUS = {
  OPEN: 'OPEN',
  RESOLVED: 'RESOLVED',
};

const SHIFT_CHANGE_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
};

module.exports = {
  USER_TYPE,
  TASK_STATUS,
  AVAILABILITY_STATUS,
  SUBSCRIPTION_STATUS,
  ASSIGNMENT_TYPE,
  LEAVE_TYPE,
  LEAVE_STATUS,
  BILLING_STATUS,
  FEEDBACK_STATUS,
  SHIFT_CHANGE_STATUS,
};