const ROLES = {
  SYSTEM_ADMIN: 'SYSTEM_ADMIN',
  ORG_ADMIN: 'ORG_ADMIN',
  PROJECT_MANAGER: 'PROJECT_MANAGER',
  PERMANENT_WORKER: 'PERMANENT_WORKER',
  TEMPORARY_WORKER: 'TEMPORARY_WORKER',
};

const TASK_STATUS = {
  PENDING: 'PENDING',
  ASSIGNED: 'ASSIGNED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
};

const AVAILABILITY_STATUS = {
  AVAILABLE: 'AVAILABLE',
  UNAVAILABLE: 'UNAVAILABLE',
  ON_LEAVE: 'ON_LEAVE',
};

const SUBSCRIPTION_STATUS = {
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  CANCELLED: 'CANCELLED',
  EXPIRED: 'EXPIRED',
};

const ASSIGNMENT_TYPE = {
  MANUAL: 'MANUAL',
  AUTO: 'AUTO',
};

module.exports = {
  ROLES,
  TASK_STATUS,
  AVAILABILITY_STATUS,
  SUBSCRIPTION_STATUS,
  ASSIGNMENT_TYPE,
};
